version: '3.7'

services:
  sample:
    container_name: inkitt-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
